import { extendTheme } from "@chakra-ui/react";

export const theme = extendTheme({
  colors: {
    transparent: "transparent",
    white: "#faf9f8",
    text: {
      gray: "#222222",
    },
  },
  fonts: {
    heading: "montserrat",
    body: "montserrat",
  },
  fontWeights: {
    hairline: 100,
    thin: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    black: 900,
  },
  fontSizes: {
    xs: "10px",
    sm: "11px",
    md: "1rem",
    lg: "1.125rem",
    xl: "1.25rem",
    "2xl": "1.5rem",
    "3xl": "1.875rem",
    "4xl": "2.25rem",
    "5xl": "3rem",
    "6xl": "3.75rem",
    "7xl": "4.5rem",
    "8xl": "6rem",
    "9xl": "8rem",
  },
  breakpoints: {
    sm: "30em",
    // These have been set
    md: "48rem",
    lg: "64rem",
    xl: "70.25rem",
  },
  textStyles: {
    a: {
      fontSize: "11px",
      fontWeight: "semibold",
      letterSpacing: "wide",
      color: "#222222",
      lineHeight: "1rem",
    },
    p: {
      fontSize: "13px",
      fontWeight: "medium",
      letterSpacing: "wide",
      color: "#222222",
      lineHeight: "1rem",
    },
    helper: {
      fontSize: "11px",
      fontWeight: "semibold",
      letterSpacing: "wide",
      color: "#707070",
      lineHeight: "1rem",
    },
    h1: {
      fontSize: ["", ""],
      fontWeight: "",
      letterSpacing: "",
      color: "#222222",
      lineHeight: "",
    },
    h2_hero: {
      fontSize: ["1.25rem", "2.265rem"],
      fontWeight: "",
      letterSpacing: "",
      color: "#222222",
      lineHeight: ["1.5rem", "1.14286"],
    },
    h2: {
      fontSize: "1.25rem",
      fontWeight: "medium",
      letterSpacing: "wide",
      lineHeight: "1.2",
      color: "#222222",
    },
    h3_hero: {
      fontSize: "0.875rem",
      fontWeight: "",
      letterSpacing: "",
      color: "#222222",
      lineHeight: "1.28571",
    },
    h3: {
      fontSize: "1.25rem",
      fontWeight: "medium",
      letterSpacing: "wide",
      lineHeight: "1.2",
      color: "#222222",
    },
    h2_footer: {
      fontSize: "0.8125rem",
      fontWeight: "bold",
      letterSpacing: "wide",
      color: "#222222",
      lineHeight: "1.25",
      textTransform: "uppercase",
      pb: "3",
    },
    a_footer: {
      fontSize: "0.625rem",
      fontWeight: "medium",
      letterSpacing: "wide",
      color: "#222222",
      lineHeight: "2.2",
      cursor: "pointer",
    },
  },
});
